name: Kingdom
version: 1.0.0
main: nl.republicmc.kingdom.KingdomPlugin
api-version: 1.17

commands:
  kingdom:
    description: "Base command of Kingdom"
    usage: /kingdom
    aliases: [kd, k]
    permission: republicmc.command.kingdom