name: Kingdom
version: 1.0.0
main: nl.republicmc.kingdom.KingdomPlugin
api-version: 1.17

commands:
  guilds:
    description: 'Manage clans'
    usage: '/clans'
    aliases: [clan]
    permission: kingdom.clans
  economy:
    description: 'Manage economy'
    usage: '/economy'
    aliases: [econ, eco, e]
    permission: kingdom.economy