name: Kingdom
version: 1.0.0
main: nl.republicmc.kingdom.KingdomPlugin
api-version: 1.17

commands:
  guilds:
    description: 'Manage guilds'
    usage: '/guilds'
    aliases: [clan, g]
    permission: kingdom.guilds
  economy:
    description: 'Manage economy'
    usage: '/economy'
    aliases: [econ, eco, e]
    permission: kingdom.economy